export const vehiclesConstants = {
  GET_ALL_BRANDS_REQUEST: 'GET_ALL_BRANDS_REQUEST',
  GET_ALL_BRANDS_SUCCESS: 'GET_ALL_BRANDS_SUCCESS',
  GET_ALL_BRANDS_FAILURE: 'GET_ALL_BRANDS_FAILURE',

  GET_ALL_MODELS_REQUEST: 'GET_ALL_MODELS_REQUEST',
  GET_ALL_MODELS_SUCCESS: 'GET_ALL_MODELS_SUCCESS',
  GET_ALL_MODELS_FAILURE: 'GET_ALL_MODELS_FAILURE',

  GET_ALL_YEARS_REQUEST: 'GET_ALL_YEARS_REQUEST',
  GET_ALL_YEARS_SUCCESS: 'GET_ALL_YEARS_SUCCESS',
  GET_ALL_YEARS_FAILURE: 'GET_ALL_YEARS_FAILURE',

  GET_VEHICLE_DETAILS_REQUEST: 'GET_VEHICLE_DETAILS_REQUEST',
  GET_VEHICLE_DETAILS_SUCCESS: 'GET_VEHICLE_DETAILS_SUCCESS',
  GET_VEHICLE_DETAILS_FAILURE: 'GET_VEHICLE_DETAILS_FAILURE',

  CHANGE_FIELD: 'CHANGE_FIELD',
  CHANGE_VEHICLE: 'CHANGE_VEHICLE',
  CLEAR_FILTERS: 'CLEAR_FILTERS',
}